### ISSUE TITLE
Building the file fails because of a missing file 

### ISSUE THREAD

**Issue by Rafiot** [coolacid/docker-misp#101]
tox seems missing in my build, causing it to fail.

it should probably be a `rm -f` so we do not have to care about that.

https://github.com/coolacid/docker-misp/blob/9ae653cd9cc3a387aa49b96d22c3ff9d65cb4391/server/Dockerfile#L76-L79

**Comment by garrit-schroeder** [comment]
This results in another error

```
Step 31/50 : RUN pip3 install --no-cache-dir /wheels/*.whl && rm -rf /wheels
 ---> Running in 0dbbffeb3de0
Double requirement given: tox==3.23.0 from file:///wheels/tox-3.23.0-py2.py3-none-any.whl (already in tox==2.7.0 from file:///wheels/tox-2.7.0-py2.py3-none-any.whl, name='tox')
ERROR: Service 'misp' failed to build : The command '/bin/sh -c pip3 install --no-cache-dir /wheels/*.whl && rm -rf /wheels' returned a non-zero code: 1

**Comment by garrit-schroeder** [comment]
Its now just Tox Version `tox-3.23.0-py2.py3-none-any.whl`

**Comment by garrit-schroeder** [comment]
What I did for now

```
    RUN rm Sphinx-1.5.5-py2.py3-none-any.whl \
           Sphinx-1.3.6-py2.py3-none-any.whl \
           tox-3.*-py2.py3-none-any.whl

**Comment by Rafiot** [comment]
yeah, I changed that too, sorry, I forgot to update the issue.

**Comment by coolacid** [comment]
Welcome to the "Python Dependency Hell" I tried to fix couple weeks back. I was getting frustrated as heck by the time I got to this point. There's a better way to remove the files we don't want, and I'll try and get that done soon.
