### ISSUE TITLE
Using compatible MISP, PyMISP, STIX and other package versions?

### ISSUE THREAD

**Issue by chrisinmtown** [coolacid/docker-misp#113]
Jason I'm sure you know that MISP delivers submodules like PyMISP set to a commit that has been tested with the server. So I was a little surprised to see that your Dockerfile just clones from HEAD, for example PyMISP. The projects don't march in lockstep; I've definitely seen the MISP PyMISP submodule lag behind the github PyMISP repo, even if not very much. Is it worth the effort to tweak that section to clone/build based on the MISP repo's submodule commits?

**Comment by coolacid** [comment]
We build all python modules outside of the running image, just in case there's left overs we don't need. This helps with size. If you have an idea to grab the expected version and build it in the build section, I'm happy to look at it.

**Comment by chrisinmtown** [comment]
I don't think the change would be large. Today the Dockerfile clones PyMISP directly and builds in that dir. I think instead it could clone MISP first, update the submodules which brings in PyMISP, then build in the MISP/PyMISP submodule directory, the MISP/cti-python-stix2 submodule directory, etc.

**Comment by coolacid** [comment]
The correct way to solve this is to have MISP tag versions and release PIP wheels directly with the expected versions to be used. Submodules are not really the best way to distribute python modules.

**Comment by chrisinmtown** [comment]
I agree with you, and the PyMISP package is available directly from PyPI. The only reason to use the MISP submodule is to ensure 100% version compatibility.  But I don't know how to convince the CIRCL MISP team to publish the tag we all should use for PyMISP :/
