### ISSUE TITLE
Add mariadb plugin caching_sha2_password.so

### ISSUE THREAD

**Issue by chrisinmtown** [coolacid/docker-misp#114]
I'm trying to use image misp-docker:core-v2.4.143a with an existing MySQL (not mariadb) instance. Apparently the default for password encryption has changed in MySQL.  On start I get this error from the MISP docker container:
```
misp_1   | ERROR 1045 (28000): Plugin caching_sha2_password could not be loaded: 
/usr/lib/x86_64-linux-gnu/mariadb19/plugin/caching_sha2_password.so: cannot open shared object file:
No such file or directory
```
The very temporary workaround was to change the password encryption type:
```
ALTER USER 'misp'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password-goes-here';
```
Would you consider adding this plugin or possibly upgrading the mariadb-client libraries to distro 10.4 or 10.5? Right now this is the installed version:
```
mysql  Ver 15.1 Distrib 10.3.27-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
```
If not I guess I'll have to figure a way to add that in my own image by FROM-ing your fine work.

Also see:
https://mariadb.com/kb/en/caching_sha2_password-authentication-plugin/

**Comment by chrisinmtown** [comment]
I finally noticed that the docker-compose.yml uses MySQL with this startup command:
```
command: --default-authentication-plugin=mysql_native_password
```
I think if you add this plugin, you might be able to drop that slight weakening of security?

**Comment by chrisinmtown** [comment]
It looks like debian release "bullseye" will use mariadb-client version 10.5:

https://packages.debian.org/search?keywords=mariadb-client

It's possible to install the 10.4 version by using the MariaDB repo as described here:

https://computingforgeeks.com/how-to-install-mariadb-on-debian/

**Comment by chrisinmtown** [comment]
Instead of installing mariadb-client from debian, I removed that package and added these lines instead:
```
  # mysql-client not available in debian repo
    RUN wget -O /tmp/mysql.deb http://repo.mysql.com/mysql-apt-config_0.8.14-1_all.deb
    RUN dpkg -i /tmp/mysql.deb
    RUN rm /tmp/mysql.deb
    RUN apt-get update && apt-get install -y mysql-client
```
So far this has good results.

**Comment by coolacid** [comment]
Thanks for digging into this. I just checked Debian buster docker image, and until there is native support from Debian, I can't support the new authentication method. While you're work around should work, I won't be making this standard.
