### ISSUE TITLE
Question re downgrading to apache

### ISSUE THREAD

**Issue by chrisinmtown** [coolacid/docker-misp#115]
Hi Jason

This issue is to ask a question. We have an internal dependency on Apache so at the moment it looks like I cannot  use your nginx-based image but have to create one that uses Apache.  :/  I checked the git history here and found this commit that appears to be the last one before you switched to nginx: 1a149d9297d3800cd961873bca6dffe6f11b3ee8

I plan to pull apache stuff from there.  But would you please share any gotchas, tricks or other intel for using apache?  I don't want to reinvent the wheel.

Thanks in advance!

p.s. I can share an email address if you don't want me cluttering your issue board like this

**Comment by chrisinmtown** [comment]
I attached my version of entrypoint_apache.sh, with a bogus file suffix bcos github issues refuse .sh files as attachments. This keeps all the features in the latest entrypoint_nginx.sh but uses apache instead.

[entrypoint_apache_sh.txt](https://github.com/coolacid/docker-misp/files/6523666/entrypoint_apache_sh.txt)

**Comment by chrisinmtown** [comment]
My version is not right yet, on start the apache server gives me this plain text instead of a nice MISP web page:
```
dispatch(new CakeRequest(), new CakeResponse(array('charset' => Configure::read('App.encoding')))); 
```
Does this look familiar?  I'm not an Apache+PHP+Cake expert.

**Comment by chrisinmtown** [comment]
I had to add this line to server/Dockerfile about line 99 to get the PHP module for Apache:
```
        libapache2-mod-php \
```

**Comment by coolacid** [comment]
Awesome work! Unfortunately, I won't be going back to apache due to the added bloat, one of the goals is to keep the image size as small as possible. But this is great documentation for someone to follow should they find themselves in the same problem.
