### ISSUE TITLE
Cannot start Cake workers due to file ownership/permissions in some environments

### ISSUE THREAD

**Issue by chrisinmtown** [coolacid/docker-misp#116]
Can't start the misp container on a mac osx laptop using VirtualBox, docker-machine and docker.  The chown command does not work as expected on the mounted volume with config files. The server shows this error repeatedly when trying to start workers:
```
misp_1          | Warning Error: include(): Failed opening '/var/www/MISP/app/Config/config.php' for inclusion (include_path='/var/www/MISP/app/Vendor/pear/console_commandline:/var/www/MISP/app/Vendor/pear/crypt_gpg:/var/www/MISP/app/Vendor/pear/pear_exception:/var/www/MISP/lib:.:/usr/share/php') in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Configure/PhpReader.php, line 72]
misp_1          | 
misp_1          | Error: No variable $config found in /var/www/MISP/app/Config/config.php
misp_1          | #0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/Configure.php(332): PhpReader->read('config')
misp_1          | #1 /var/www/MISP/app/Config/bootstrap.php(86): Configure::load('config')
misp_1          | #2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/Configure.php(98): include('/var/www/MISP/a...')
misp_1          | #3 /var/www/MISP/app/Lib/cakephp/lib/Cake/bootstrap.php(432): Configure::bootstrap(true)
misp_1          | #4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(148): require('/var/www/MISP/a...')
misp_1          | #5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(100): ShellDispatcher->_bootstrap()
misp_1          | #6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(54): ShellDispatcher->_initEnvironment()
misp_1          | #7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(65): ShellDispatcher->__construct(Array)
misp_1          | #8 /var/www/MISP/app/Console/cake.php(32): ShellDispatcher::run(Array)
misp_1          | #9 {main}
```
The cause is that the config.php file cannot be read. The docker-compose mounts local directories to the container for config files. I see that on first start the entrypoint script populates the Config/ directory with default files. Then the entrypoint script attempts this:
```
echo "... chown -R www-data.www-data /var/www/MISP ..." && find /var/www/MISP -not -user www-data -exec chown www-data.www-data {} +
...
echo "... chmod 600 /var/www/MISP/app/Config/config.php /var/www/MISP/app/Config/database.php /var/www/MISP/app/Config/email.php ... " && chmod 600 /var/www/MISP/app/Config/config.php /var/www/MISP/app/Config/database.php /var/www/MISP/app/Config/email.php
```
The chown returns no error but it has no effect -- the files remain owned by a UID other than www-data.  Then the chmod makes the files completely unreadable by the Nginx process.

I'm not certain of an appropriate solution here.  My brutal workaround was to comment out the line in entrypoint_nginx.sh that does the chmod, leave them default modes like 644. Would you consider adding Dockerfile "ARG" to make the chmod line optional for this special case?

Hope this helps, Jason.

**Comment by coolacid** [comment]
This sounds like a bug when using docker on mac. Unfortunately, I'm not at a place where I can support this on a mac - as a matter of fact, I normally tell people to run a full Linux VM on mac to work with docker for these specific problems.
