### ISSUE TITLE
misp-modules docker container failed to find library libGL.so.1

### ISSUE THREAD

**Issue by chrisinmtown** [coolacid/docker-misp#118]
On start of the misp-modules container I see the following errors:
```
misp-modules_1  | 2021-05-24 14:15:29,831 - misp-modules - WARNING - MISP modules ocr_enrich failed due to libGL.so.1: cannot open shared object file: No such file or directory
misp-modules_1  | WARNING:misp-modules:MISP modules ocr_enrich failed due to libGL.so.1: cannot open shared object file: No such file or directory
...
misp-modules_1  | 2021-05-24 14:15:31,137 - misp-modules - WARNING - MISP modules qrcode failed due to libGL.so.1: cannot open shared object file: No such file or directory
misp-modules_1  | WARNING:misp-modules:MISP modules qrcode failed due to libGL.so.1: cannot open shared object file: No such file or directory
```
I guess OpenGL libraries really depend on the hardware, but here we're talking about docker containers running on machines that probably have absolutely no graphics cards. This link helped me understand the complexity:

https://www.codeweavers.com/support/wiki/Diag/MissingLibGL

FWIW I experimented with installing package `libglu1-mesa-dev` which dropped a bunch of libGL* files into directory /usr/lib/x86_64-linux-gnu/ including libGL.so.1 but I'm not at all certain that's the right way to solve this missing dependency.

**Comment by coolacid** [comment]
Odd, I don't know why those are trying to use libGL, something to look at - but this should probably be a MISP-modules bug, not a docker specific bug.

**Comment by chrisinmtown** [comment]
Yes I agree that this should be a modules bug, I guess the prereqs omit something required by ocr_enrich module, I'll close this now.
