### ISSUE TITLE
Building modules from v2.4.144 fails, chardet

### ISSUE THREAD

**Issue by Kagee** [coolacid/docker-misp#121]
`ERROR: Double requirement given: chardet==4.0.0 from file:///wheel/chardet-4.0.0-py2.py3-none-any.whl (already in chardet==3.0.4 from file:///wheel/chardet-3.0.4-py2.py3-none-any.whl, name='chardet')`

Faup added chardet as a unversioned dependency https://github.com/stricaud/faup/commit/b5c82fb49169d1386ca215fc128d08ddcbc87664 so it defaults to 4.0.0.
misp-modules has a dependency on chardet 3.0.4 https://github.com/MISP/misp-modules/blob/main/REQUIREMENTS#L30

A quick read-through of https://github.com/chardet/chardet/releases/tag/4.0.0 indicated that there were no API changes, so either library could in theory swap the the other version?

**Comment by coolacid** [comment]
Of course.. This also needs to be an issue in MISP-Modules so they are aware of the double requirement.

**Comment by chrisinmtown** [comment]
Thanks, I just hit this build problem, so nice that someone already solved it!
