### ISSUE TITLE
Add logrotate to the cron

### ISSUE THREAD

**Issue by chrisinmtown** [coolacid/docker-misp#122]
MISP writes logs but logs should not grow forever. A crontab should invoke logrotate, and the system will need a logrotate config file pointing at /var/www/MISP/app/tmp/logs

**Comment by chrisinmtown** [comment]
Logrotate behavior is specific to each distro.  In RHEL installing the logrotate RPM adds directory /etc/cron.daily with file logrotate.  Since docker-misp already has an entrypoint_cron.sh that runs a cron daemon, I think only two changes are required:
1. Add logrotate to the list of packages installed in the Dockerfile
2. Add a new file to /etc/logrotate.d named 'misp' with content like this:
```
/var/www/MISP/app/tmp/logs/*.log {
    su apache apache
    rotate 30
    dateext
    missingok
    notifempty
    compress
    daily
    size 50M
    maxsize 500M
    copytruncate
}
```

**Comment by coolacid** [comment]
I'd be of the mindset that you bind-mount the log directory into the host, and have the host handle your logs. Log rotate, filebeat, syslog what have you. Typically you don't run more services then needed in the docker container. The only reason why we do currently is there was no easy way around it.
