### ISSUE TITLE
Missing build for MISP_TAG=v2.4.147 on DockerHub

### ISSUE THREAD

**Issue by ITSEC-DACHSER** [coolacid/docker-misp#132]
Hello!

Looks like there is the latest MISP build (2.4.147) missing on DockerHub -> https://hub.docker.com/r/coolacid/misp-docker/tags?page=1&ordering=last_updated
Last change was a month ago.

Can you please recheck ?
Thank you.

**Comment by coolacid** [comment]
I've meant to write an issue, and pin it a few times, but real life got in the way.

Docker hub no longer allows me to auto-generate images without being on their paid pro plan. While $5 a month seems like a small amount, all of my $5 a month items do add up.

**Comment by coolacid** [comment]
I've bit the bullet and paid docker, builds are being done now.
