### ISSUE TITLE
Performance running on RHEL using Podman

### ISSUE THREAD

**Issue by jezkerwin** [coolacid/docker-misp#133]
I'm attempting to run MISP on a RHEL system using podman however the performance is really slow. It takes quite a long time for the MISP container to start compared to running it on Ubuntu system. 

I'm not sure what to look for to begin troubleshooting so would appreciate any assistance.

**Comment by jezkerwin** [comment]
I'm attempting to build the image from scratch according to the README, perhaps that might help with performance.

**Comment by coolacid** [comment]
Do you have a lot of files in of the mounted directories? Is this on a slow NFS drive? Does your NFS drive do snapshotting causing a lot of files?

**Comment by jezkerwin** [comment]
Turns out the issue was VMware Workstation on my Win10 dev box. 
VirtualBox and vSphere don't have the issue
