### ISSUE TITLE
Add support for Postgres

### ISSUE THREAD

**Issue by irl** [coolacid/docker-misp#134]
In our deployment we already have a Postgres server running, and MISP supports Postgres. Would it be possible to pass those variables through to the container via the docker-compose file and use that rather than MySQL?

**Comment by coolacid** [comment]
I don't really want to manage multiple DB initialisers. I've seen this attempted in other projects and adds a whole lot of complexity to the startup. 

However, if you manually setup the Database, and configuration files then ensure `INIT` environment variable is false, you bypass all the MySQL specific setups. (I Think).

**Comment by irl** [comment]
If I did the work, would you accept a pull request? It's going to add an extra function in the initialisation but I'm not convinced it'll add that much complexity. (I'm probably going to do the work anyway, because we need it.)

If it does turn out to be more complicated to maintain than it would be to maintain a MySQL installation for the deployment then I'd not do it, so that'd be where I draw the line.

**Comment by coolacid** [comment]
The entrypoint_nginx file is starting to get a little long, and probably should be broken up better into stages/items. 

The biggest part I find handling this is ensuring execution path, and validating the database is ready for initialization. 

I'm always willing to entertain PRs. I'll try and help guide how I'd envision it working.

**Comment by Kagee** [comment]
MISP on PostGRESQL is not supported and has not been updated in ages. Best is to stay away from it.
