### ISSUE TITLE
 nginx: [emerg] socket() [::]:443 failed (97: Address family not supported by protocol)

### ISSUE THREAD

**Issue by Ari-R** [coolacid/docker-misp#147]
Hi,

I am trying to get this misp container working. I clone the git repo onto the machine and then try docker-compose up from the folder created. When doing this it just goes through the same setup constantly (misp_1) the only error I can see that comes up is nginx: [emerg] socket() [::]:443 failed (97: Address family not supported by protocol). 

Does anyone know how to fix this and be able to run this container?

**Comment by coolacid** [comment]
You're machine doesn't support IPv6. There is an environment variable to disable IPv6.
