### ISSUE TITLE
Distributed Install

### ISSUE THREAD

**Issue by clopmz** [coolacid/docker-misp#149]
Hi @coolacid ,

Is it possible to accomplish a distributed install with your docker images? Actually I am using mysql and redis components in another docker's host I would like to reuse them, like for example:

HostA: mysql, redis
HostB: misp, misp-modules (your docker's images).

Regards

**Comment by coolacid** [comment]
Yes - I do this via Ansible at $DayJob. Just need to provide the proper configuration to the MISP instance.

**Comment by clopmz** [comment]
Is it possible to accomplish adding options in docker-compose.yml file? For example:

REDIS_HOST=x.x.x.x
REDIS_PORT=3444
REDIS_DB=13
.....

and so on ....

**Comment by coolacid** [comment]
These items are currently not available as environment variables - there are two open PRs to make this an option with different approaches. 

I personally have my deployment engine handle the configuration files, and not environment variables, this way changes are tracked in our git repo, and secrets come from our vault.

**Comment by clopmz** [comment]
Excuse my ignorance @coolacid , but in docker technology I am a newcomer .... Any example?

**Comment by coolacid** [comment]
Run the docker-compose project first time, and stop it - it will generate configuration file, which you can then modify to point to the hosts you expect.

**Comment by clopmz** [comment]
Yep ... perfect!! .... Many thanks @coolacid
