### ISSUE TITLE
Avoid env variable HOSTNAME

### ISSUE THREAD

**Issue by paalbra** [coolacid/docker-misp#151]
The env variable `HOSTNAME` is used to set the `baseurl` of MISP. This could be problematic. E.g when using podman and a pod you're not able to set the variable:

```
$ podman pod create --name=testpod
304ac07b8e785b46bf98ba1c5bf7019b7891accea570da942a26e60d8adb0569
$ podman run --pod=testpod -e HOSTNAME=foo --rm --entrypoint bash coolacid/misp-docker:core-latest -c 'echo $HOSTNAME'
testpod
```

I suggest to rename it to something like `BASEURL`.

https://github.com/coolacid/docker-misp/blob/83ab4245b87861ae802e93e30fdad779f21d96e7/server/files/entrypoint_nginx.sh#L37

Since this will be a breaking change, backward compatibility could be added with something like:

```bash
if [[ "$HOSTNAME" =~ ^https?:// ]]; then
    BASEURL="$HOSTNAME"
fi
```

**Comment by paalbra** [comment]
Actually. Regarding backward compatibility. We could simply just do this:
```bash
if [[ -z "$BASEURL" ]]; then
    echo HOSTNAME environment variable is deprecated. Use BASEURL instead. 1>&2
    BASEURL="$HOSTNAME"
fi

**Comment by coolacid** [comment]
This looks good, would you like to PR this?

**Comment by paalbra** [comment]
> This looks good, would you like to PR this?

I could look into it. I might have some spare time today actually. Maybe I'll be able to produce something later :+1:
