### ISSUE TITLE
TLS Support

### ISSUE THREAD

**Issue by kraken8585** [coolacid/docker-misp#152]
Hi Jason,

I have an issue when initiating an API request from the MISP docker to Azure Logic App. It works fine with POSTMAN but I'm getting an error on the LogicApp end indicating a failure with the securechannel transport. Diving deeper into the network packets, I notice that POSTMAN uses TLS1.0(Request succeeded) while Azure uses TLS1.2(Request Failed) during the client/server handshake. Any idea how I can fix this? Appreciate the help here. Thanks.

**Comment by coolacid** [comment]
I don't see where this would be an issue with the docker container, but you also didn't include any logs. 

There was bugs with CakePHP and MISP in 2017 regarding TLS1.2, so I have to assume TLS1.2 is supported. 

Is it possible the SSL certs you're connecting to is LetsEncrypt based and not providing the correct CA Cert join hints?

**Comment by kraken8585** [comment]
Fixed it. I accidently enabled higher security of ssl in the yaml configuration
