### ISSUE TITLE
Update to Debian Bullseye

### ISSUE THREAD

**Issue by coolacid** [coolacid/docker-misp#155]
I've created a new branch for updating to Debian BullsEye, this brings PHP to 7.4, as well as python to 3.9.  The branch can be found here: https://github.com/coolacid/docker-misp/tree/bullseye

I'd love some people to build and test this branch before I merge it into master. I've very sorry for waiting until the last moment to do this work. 

This solves #128 and #146

**Comment by fukusuket** [comment]
Thank you for updating 😀
After building the Docker image in my environment, I tested it with the following, and there was no problem ^^

## Operation
- Event/Attribute add/delete/modify
- Feed import

## Revision
https://github.com/coolacid/docker-misp/commit/0510cfe7d0e29eb0a90a5a85bcb9905b6c20d318

## Enviroment
```
root@lin:~# uname -a
Linux lin 5.11.0-44-generic #48~20.04.2-Ubuntu SMP Tue Dec 14 15:36:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
root@lin:~# cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"
root@lin:~# docker -v
Docker version 20.10.12, build e91ed57
root@lin:~#
```

**Comment by coolacid** [comment]
Merged into Master and now default use.
