### ISSUE TITLE
How to deploy behind Traefik

### ISSUE THREAD

**Issue by pietrogu** [coolacid/docker-misp#157]
Hi,

i am trying to create a dockerized MISP behind Traefik, but i'm having some difficult due to the complexity of the project
Anyone can help me with a working config?

Regards,
Pietro

**Comment by coolacid** [comment]
I took a quick look at Traefik to see if I could see anything specifically to help, however, I don't have the time to learn another load balancer. It's beyond the scope of this project to help set the container like that, so I can't help you. Sorry.
