### ISSUE TITLE
Update MISP 2.4.156

### ISSUE THREAD

**Issue by ITSEC-DACHSER** [coolacid/docker-misp#162]
Hi,

is it planned to bring up a new built with the latest MISP version (2.4.156)? The current version used is 2.4.153.

BR

**Comment by Kagee** [comment]
@coolacid .156 also includes important security updates, so it would be nice. That sais, 157 is also not far away, to fix some GPG bugs in 156. I've build the docker with the lates master branch (MISP_TAG=2.4), and it appears to work withoug problems.

**Comment by coolacid** [comment]
Sorry, real life stuff has me pretty busy.

Tagged 154 thru 156 and they should start building soon .

**Comment by ITSEC-DACHSER** [comment]
Absolutely no problem. We understand this and appreciate your work on this project. Thank you very much.
