### ISSUE TITLE
DB schema errors

### ISSUE THREAD

**Issue by VVX7** [coolacid/docker-misp#17]
Docker-compose up on 2.4.121 builds the instance but MISP complains the DB schema doesn't match the expected schema.

![Screenshot_2020-02-18_23-14-29](https://user-images.githubusercontent.com/46228229/74801256-0e860600-52a4-11ea-8f2e-8383a849e974.png)

**Comment by coolacid** [comment]
Forgot about this - I believe this is related to the docker mysql and permissions. Clearly, a lot of those items are there or you wouldn't be able to login. Something I def need to fix tho.

**Comment by coolacid** [comment]
Totally NOT a permissions issue, but appears to be a incompatibility with new mysql? 

https://github.com/MISP/MISP/blob/38cdd5477f058769cb9abbcda87ff89ed43ec3e8/app/Model/Server.php#L4594

`$keyedActualColumn[$column['column_name']] = $column`

However, in mysql, the column_name is actually uppercase:
```
MySQL [(none)]> SELECT column_name, is_nullable, data_type, character_maximum_length, numeric_precision, datetime_precision, collation_name, column_default FROM information_schema.columns WHERE table_schema = 'misp' AND TABLE_NAME = 'admin_settings';
+-------------+-------------+-----------+--------------------------+-------------------+--------------------+----------------+----------------+
| COLUMN_NAME | IS_NULLABLE | DATA_TYPE | CHARACTER_MAXIMUM_LENGTH | NUMERIC_PRECISION | DATETIME_PRECISION | COLLATION_NAME | COLUMN_DEFAULT |
+-------------+-------------+-----------+--------------------------+-------------------+--------------------+----------------+----------------+
| id          | NO          | int       |                     NULL |                10 |               NULL | NULL           | NULL           |
| setting     | NO          | varchar   |                      255 |              NULL |               NULL | utf8_bin       | NULL           |
| value       | NO          | text      |                    65535 |              NULL |               NULL | utf8_bin       | NULL           |
+-------------+-------------+-----------+--------------------------+-------------------+--------------------+----------------+----------------+
3 rows in set (0.001 sec)
```

Current running fix would be to add the following line just prior to https://github.com/MISP/MISP/blob/38cdd5477f058769cb9abbcda87ff89ed43ec3e8/app/Model/Server.php#L4553
`$column_schema['columns'] = array_change_key_case($column_schema['columns'],CASE_LOWER);`

This forces all the keys lowercase, I want to see if there's a mysql patch note before opening a PR with misp.

**Comment by coolacid** [comment]
This appears to be a mysql setting: https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_lower_case_table_names

Personally, I think MISP should force the keys low, either in PHP, of using a LOWER() call in the SQL query to ensure it is as expected.

**Comment by coolacid** [comment]
Also, `sightingdbs` isn't in MISP/INSTALL/MYSQL.sql which yields benign deltas in the collation

**Comment by iglocska** [comment]
Wow, interesting. Yeah that makes sense with the case change, why on earth change stuff like that between mysql versions /rage.

For the sightingdbs missing - will bring MYSQL.sql up to date, but generally it being behind the expected schema is fine, the upgrade scripts on first login should take care of that.

**Comment by coolacid** [comment]
https://github.com/MISP/MISP/pull/5654

**Comment by coolacid** [comment]
Merged, closing.
