### ISSUE TITLE
Installing new MISP Modules

### ISSUE THREAD

**Issue by derfel1989** [coolacid/docker-misp#172]
Hi guys,

To avoid any issue in the MISP stack during modules installation. How can I install new modules on the `docker-misp_misp-modules_1` container?

Also, is necessary run the script "/usr/local/lib/python3.9/site-packages/pymisp/data/misp-objects/tools/**updated.sh**" to update modules?

Thank you in advance.

**Comment by coolacid** [comment]
All modules are already installed and enabled. I'm not sure what you're asking here.
