### ISSUE TITLE
Not able to build misp

### ISSUE THREAD

**Issue by abhijeetasawant** [coolacid/docker-misp#178]
Following error shown while building misp:

Step 40/70 : COPY --from=php-build /usr/lib/php/${PHP_VER}/ssdeep.so /usr/lib/php/${PHP_VER}/ssdeep.so
 ---> 7cce9296475e
Step 41/70 : COPY --from=php-build /usr/lib/php/${PHP_VER}/rdkafka.so /usr/lib/php/${PHP_VER}/rdkafka.so
 ---> 8cb3536b1cba
Step 42/70 : COPY --from=php-build /usr/lib/php/${PHP_VER}/brotli.so /usr/lib/php/${PHP_VER}/brotli.so
 ---> 848458b20255
Step 43/70 : COPY --from=composer-build /tmp/Vendor /var/www/MISP/app/Vendor
 ---> 99eadc04e104
Step 44/70 : COPY --from=composer-build /tmp/Plugin /var/www/MISP/app/Plugin
COPY failed: stat tmp/Plugin: file does not exist

**Comment by coolacid** [comment]
Try upgrading your docker and docker-compose.
