### ISSUE TITLE
MISP docker image version

### ISSUE THREAD

**Issue by VVX7** [coolacid/docker-misp#18]
When 2.4.121 tag is used the actual MISP version is v2.4.120 88894fc2e5773e10ae717ab87fea700693fb7dae as reported in the diagnostic.

`cat .env 
MISP_TAG=2.4.121
PHP_VER=20180731`

![Screenshot_2020-02-18_23-17-54](https://user-images.githubusercontent.com/46228229/74801418-7f2d2280-52a4-11ea-8ee6-997cd54eeffa.png)

**Comment by coolacid** [comment]
This appears to be a bug in MISP: https://github.com/MISP/MISP/blob/2.4/VERSION.json shows the wrong version.

**Comment by coolacid** [comment]
Confirmed: 2.4.121 is 88894fc2e5773e10ae717ab87fea700693fb7dae and updating the VERSION.json file bumps to green.

Phew, had me worried there.

**Comment by VVX7** [comment]
Sorry, I should have checked the commit hash.

**Comment by coolacid** [comment]
:+1:
