### ISSUE TITLE
MISP Not Connecting to the Database

### ISSUE THREAD

**Issue by asterictnl-lvdw** [coolacid/docker-misp#180]
What I have done:

I am currently testing ThePhish with their latest versions of TheHive, Cortex and of course MISP. I do need MYSQL. But all the things work except for MISP. 

I tried it with the following versions: 5.7 8.0.19 and 8.2.26
redis: 5.0.6 and 6.2.5

I either get the error of the database could not be found or that the IP does not have permission to enter the MySQL database.

I used the template on here of the docker-compose.yml, the one that ThePhish uses (the section of MISP and it's DB) and https://ls111.me/thehive-cortex-misp-installation-using-docker-compose/ who got it working as well. 

Do you have any clue on how to get MISP working along with the latest versions of Cortex, TheHive and ThePhish?

Thanks in advance.

**Comment by coolacid** [comment]
Those sound like configuration and/or permission errors, and not specific to this docker image. Unfortunately, I don't use any of those other tools and was hoping someone else might be able to chime in and help. You're best bet might be one of the end user support options for one of those projects.
