### ISSUE TITLE
Can we Access docker-misp on the Network from another system (not just localhost)

### ISSUE THREAD

**Issue by adnanshahz2018** [coolacid/docker-misp#183]
Hi, 
First of all thanks for the project. It is wonderful.

Actually I want to **_Access it over my Private Network_**, from other systems as well.
However it is running only on "**_localhost_**" for now.

Please Advise
Thanks

**Comment by Kagee** [comment]
This has nothing to do with this docker, but is something local to your setup i.e. firewalls or routing. The compose file will by default bind to port 80 and 443 on all interfaces, and should thus be available on more than localhost.

**Comment by CyberKaizen** [comment]
I've identified that no matter what changes are made on the OS or otherwise, coolacid's MISP docker is the only one that there is somehow no way to get it accessible via anything other than localhost. After 12 hours of trying.

**Comment by coolacid** [comment]
You've provided no details here. What OS? How are you launching it? What is your docker and MISP configurations. 

You're the only one that has this issue as this docker image is used by multiple organisations and trainers.

**Comment by CyberKaizen** [comment]
OS: Ubuntu 22.04 amd64
I've been launching it per instructions on a VMware ESXi hosted VM.

**Comment by coolacid** [comment]
Please provide requested information. Configurations and Logs. Feel free to srub out any sensitive user, password or secrets.

**Comment by coolacid** [comment]
I'm also going to note, you're not OP - You're issue may be different and should probably be it's own ticket instead of high jacking someone else's.

**Comment by CyberKaizen** [comment]
I'll make a separate issue then. Apologies.

**Comment by helospro** [comment]
can i Access from my laptop if installed MISP on server ( not localhost )?

**Comment by coolacid** [comment]
@helospro  This is a docker question, not a MISP-Docker question. 

OP hasn't responded, closing this issue as stale.
