### ISSUE TITLE
Process split

### ISSUE THREAD

**Issue by pburgisser** [coolacid/docker-misp#190]
Hello,

I was wondering how it would be complicated to split the different processes to different containers ?
It's a best practice to run nginx and php-fpm in two different containers.

Also, in a k8s environment, can we run the crontab as k8s crontabs ?

Thanks for your hints
Philippe

**Comment by coolacid** [comment]
The reason this exists is that best practice. However, php-fpm doesn't provide access to the static files on it's own, only nginx. We could side-car nginx and php-fpm, but that become much more complicated should an end user wish to deploy with something other then the reference docker-compose here. 

As for K8s, I don't work with it, so I couldn't be sure.
