### ISSUE TITLE
Arm64

### ISSUE THREAD

**Issue by juazunco** [coolacid/docker-misp#191]
I wanted to know if I could run it on arm64 architecture.

Thank you in advance for all your support and help.

**Comment by jthDEV** [comment]
You may. But to do so, you will need to upgrade the mySQL reference  in the `docker-compose.yml`.
Open the file and change line 12 to e.g. `image: mysql:8.0.30`

**Comment by sigsegv1989** [comment]
@juazunco I tried to run it on arm64 architecture and works for me by replacing MySQL image with `arm64v8/mysql:8.0.31`
in` docker-compose.yml`
Also, run `docker-compose -f docker-compose.yml build` in your repo to build the `coolacid/misp-docker:core-latest` and `coolacid/misp-docker:modules-latest` images locally to support arm64
