### ISSUE TITLE
MISP-module yara_query not working properly

### ISSUE THREAD

**Issue by sva-mk** [coolacid/docker-misp#193]
Hey,

i am trying to use the MISP-module named "yara_query" to generate yara rules from hash-values.
But unfortunately, I have some difficulties using it. 
It throws the following error during the generation of a yara rule based on a md5 value.
`Syntax error: line 4: invalid field name "md5"`

The Module shows up in the maintenance section of the MISP and has been enabled as usual. 

I also tried to debug the module via curl but I get the same error response.
`curl -s http://<docker-container-ip>:6666/query -H "Content-Type:application/json" --data '{"module": "yara_query", "md5": "0cbc6611f5540bd0809a388dc95a615b"}' -X POST`

Additionally, I tested the curl request against a clean bare-bone MISP installation and got a valid response
`{"results": [{"types": ["yara"], "values": "import \"hash\"\r\nrule MD5 {\r\n\tcondition:\r\n\t\thash.md5(0, filesize) == \"0cbc6611f5540bd0809a388dc95a615b\"\r\n}"}]}`. 
Therefore, I can ensure that the module itself is working properly.

**Comment by coolacid** [comment]
Possibly related: https://github.com/VirusTotal/yara/issues/757

**Comment by sva-mk** [comment]
Thanks a lot for your fast response and fix!
