### ISSUE TITLE
chown: cannot dereference '/var/www/MISP/INSTALL/old/INSTALL.ubuntu1604.txt': No such file or directory

### ISSUE THREAD

**Issue by helospro** [coolacid/docker-misp#195]
![image](https://user-images.githubusercontent.com/100141161/201890366-a108bf21-6254-4453-88ac-d5136bf4d3fa.png)

help.. i got error like this.

**Comment by sva-mk** [comment]
These logs seem fine for me - have you tried waiting 2-5 mins until the webfrontend started?

**Comment by coolacid** [comment]
This is not an error that would cause any issues to the start up of the system.
