### ISSUE TITLE
Cert problem 

### ISSUE THREAD

**Issue by vitorrossano** [coolacid/docker-misp#200]
I'm deployment a instance of MISP using rancher (2.6.4), and include a SSL certificate, but I'm getting  "ERR_TOO_MANY_REDIRECTS" error, can you help me?

**Comment by coolacid** [comment]
This isn't a support channel, I'd suggest the GITTER channels linked in this and MISP's repos.

However, I suspect you're forcing SSL, but don't have SSL turned on in MISP so it's redirecting back and forth. Make sure both your web server and MISP is configured correctly.
