### ISSUE TITLE
MISP Docker Installation issue

### ISSUE THREAD

**Issue by BabaMajid** [coolacid/docker-misp#201]
Hi,
I'm simply pulling the latest image and trying to run it in docker as Ubuntu my base OS. 
**docker container run coolacid/misp-docker:core-latest -p 127.0.0.1:80:80**  is used for running docker image.
I'm getting below issue, can someone tell me what that is and what is the way forward.

_Error: Format string 'CRON_USER_ID=%(ENV_CRON_USER_ID)s' for 'environment' contains names ('ENV_CRON_USER_ID') which cannot be expanded. Available names: ENV_DEBIAN_FRONTEND, ENV_HOME, ENV_HOSTNAME, ENV_LC_CTYPE, ENV_PATH, ENV_PWD, ENV_SHLVL, ENV__, group_name, here, host_node_name, numprocs, process_num, program_name in section 'program:cron' (file: '/etc/supervisor/conf.d/supervisord.conf')
For help, use /usr/bin/supervisord -h_

**Comment by vitorrossano** [comment]
When I geted this  same error, using Kubernetes/Rancher I just config de environment variables like says in docker-compose to fixed this error.

**Comment by BabaMajid** [comment]
@vitorrossano you mind sharing the exact environment variable you set. I have used 'export  CRON_USER_ID=1' in terminal but that didn't solve anything.

**Comment by coolacid** [comment]
You need to ensure the environment variables are correctly set. See the docker-compose file for the list.
