### ISSUE TITLE
No Misp folder in /var/www

### ISSUE THREAD

**Issue by ashifly** [coolacid/docker-misp#202]

**Comment by ashifly** [comment]
I have installed this docker in Digital Ocean & there is no Misp directory in /var/www. Also My GUI looks like 
![Uploading image_2023-01-15_16-38-55.png…]()

**Comment by ashifly** [comment]
I have installed this docker in Digital Ocean & there is no Misp directory in /var/www. Also My GUI looks like
![image_2023-01-15_16-38-55](https://user-images.githubusercontent.com/76905413/215962870-c37a7acd-8353-45bf-9822-a04539338af7.png)

**Comment by coolacid** [comment]
No details in ticket - closing.
