### ISSUE TITLE
Security vulnerabilities in `core-v2.4.167a`

### ISSUE THREAD

**Issue by brsolomon-deloitte** [coolacid/docker-misp#206]
`coolacid/misp-docker:core-v2.4.167a` has multiple critical and high severity security vulnerabilities based on use of outdated software.

- git (used in git-man, git) version 1:2.30.2-1 has 8 vulnerabilities
- curl (used in libcurl3-gnutls, libcurl4) version 7.74.0-1.3+deb11u3 has 7 vulnerabilities
- wheel version 0.34.2 has 2 vulnerabilities
- py version 1.11.0 has 1 vulnerability
- pip version 20.3.4 has 1 vulnerability
- tiff (used in libtiff5) version 4.2.0-1+deb11u1 has 35 vulnerabilities
- sudo version 1.9.5p2-3 has 1 vulnerability
- mariadb-10.5 (used in mariadb-client, mariadb-common, mariadb-client-core-10.5, mariadb-client-10.5, libmariadb3) version 1:10.5.18-0+deb11u1 has 1 vulnerability

Reported by: Prisma Cloud / Twistlock Defender.

At the very least please consider a:

```
RUN apt-get autoremove --purge -y curl && \
    apt-get update && apt-get upgrade -y && \
    apt-get clean && rm -rf /var/lib/apt/lists /var/cache/apt/archives
```

**Comment by derfel1989** [comment]
[Is this update capable to solve these vulnerabilities?](https://www.misp-project.org/2023/02/16/MISP.2.4.168.released.html/)

**Comment by coolacid** [comment]
The docker image is based on Bullseye:Slim https://github.com/coolacid/docker-misp/blob/master/server/Dockerfile#L84 

I rely on upstream docker image to be updated at time of build. I do not rebuild images once they are built. 

If you feel it's necessary, feel free to use this as a base image and run the updates locally. 

@derfel1989  -- The listed fixes is in MISP, not the OS layer. A new build may solve some of these issues assuming the upstream docker image is updated.

**Comment by derfel1989** [comment]
Thank you for the prompt response.

**Comment by brsolomon-deloitte** [comment]
@coolacid are `git` and `sudo` really needed as part of the final image? It seems like they might just be required for the build.

**Comment by coolacid** [comment]
Sudo: https://github.com/coolacid/docker-misp/blob/master/server/files/entrypoint_workers.sh#L14

Git is used internally by MISP for version validations.

**Comment by brsolomon-deloitte** [comment]
Okay, thanks for your response and closing per your suggestion above.
