### ISSUE TITLE
Custom objects copied to MISP object path are overwriten by default objects in container up

### ISSUE THREAD

**Issue by franciscoGolondrina** [coolacid/docker-misp#208]
Hello, I'm trying to copy custom objects from local files to the MISP container using COPY function in server/Dockerfile. I want to copy the content of the folder object_templates into the default MIPS objects path (/var/www/MISP/app/files/misp-objects/objects). 

![image](https://user-images.githubusercontent.com/125904063/220334879-3be93c71-e3fa-4961-8b59-267dd3defbc7.png)

The image building is correctly done but when I see the content of /var/www/MISP/app/files/misp-objects/objects in the MISP container, none of my objects where there. But I tried to copy the folder into another path (for example /tmp) and it works correctly

![image](https://user-images.githubusercontent.com/125904063/220335419-402c7459-9ed7-454d-8287-26d87240fe35.png)

Kind regards.

**Comment by coolacid** [comment]
`/var/www/MISP/app/files` should be volume mounted. Thus, you can't copy things into that directory prior launching. 

This is a docker issue, not related to this project. 

I suggest you copy the files into the correct place in the volume mount not in the docker file.

**Comment by franciscoGolondrina** [comment]
The problem is that when I `docker-compose up` after I move the new objects into `/var/www/MISP/app/files/misp-objects/objects`, the objects are overwritten.
