### ISSUE TITLE
All workers are dead after starting container

### ISSUE THREAD

**Issue by AxoniusTK** [coolacid/docker-misp#209]
Hello,

All workers are starting dead when the container is starting.
I deployed it on AWS ECS.
Using RDS for database and Elasticache for Redis.
I also mounted several external volumes.
```
/var/www/MISP/app/Config/
/var/www/MISP/app/tmp/logs/
/var/www/MISP/app/files/
/var/www/MISP/app/webroot/img/custom/
```
I'm not using certificates, so the cert folder is not relevant.

MISP is still working well, and if I'm hitting the "Restart Dead Workers" button after the container starts seems like all workers are working as expected.
Have you seen something like that before?

![image](https://user-images.githubusercontent.com/112958394/220375750-c8cddf76-0841-45f8-8db1-4507fe8dabcb.png)

This is the log I'm seeing after `entrypoint_workers.sh` is running.
The hidden string is the value I used in the `HOSTNAME` environment variable.
![image](https://user-images.githubusercontent.com/112958394/220377102-d969ba3a-75e5-4c2c-ab60-a409878511c2.png)

Thanks! :)

**Comment by BlackFrosty** [comment]
Hi, 

I have a similar problem on AWS, except that it is limited to the workers being unable to stop (with the same failed to parse argument [BASEURL]). But the following worker starting sequence is done correctly.

So as time goes by, each hour, 5 new workers are added to the load, until the RAM usage is maxed out and the EC2 crashes...
I was wondering what you did to correct your issue?

Thanks !

**Comment by stone-hiro** [comment]
Hi,

I have a similar problem on AWS, too.
The cause of this problem may be that we have used HOSTNAME environment variable.
I find following notice in [ECS Develper Guide](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#container_definition_environment)

> If you're using the awsvpc network mode, the hostname parameter isn't supported.

Currently, misp-docker uses BASEURL environment variable instead HOSTNAME (#151), the problem may not occur.
I will confirm if my idea is correct and comment this issue's page.
