### ISSUE TITLE
Connect with communities - Email error

### ISSUE THREAD

**Issue by JohanPhom** [coolacid/docker-misp#210]
Hi everyone,

I would like to connect my MISP instance to an other community, but when I make a request through the GUI I get an error. When I check the logs inside the main container in /var/www/MISP/app/tmp/logs/error I have this:

```
2023-02-24 12:53:43 Error: [SendEmailException] The message could not be sent.
Request URL: /communities/requestAccess/3ab3a65a-0171-401a-9895-8d42bc7bed7c
Stack Trace:
#0 /var/www/MISP/app/Model/User.php(829): SendEmail->sendExternal()
#1 /var/www/MISP/app/Controller/CommunitiesController.php(147): User->sendEmailExternal()
#2 [internal function]: CommunitiesController->requestAccess()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#6 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#7 {main}
```

I know some modifications have to to made in the email.php, but I don't understand which config to use and how. In the class EmailConfig there are $default, $smtp, and $fast. Which one should I configure ? And how ? I just want to connect to an other community.

Thank to anyone who wishes to help.

**Comment by JohanPhom** [comment]
Just needed to install mail utility on the docker container.

`apt-get install sendmail`

**Comment by coolacid** [comment]
While that will work, I wouldn't suggest that. I would suggest you configure the email configuration to point at your mail server. 

For support of MISP, I would also suggest reaching out to MISP devs as they are more apt to support the software.

**Comment by JohanPhom** [comment]
I would like to configure the email.php to point to my exchange server as you suggest, however to authenticate I need to put clear credentials in the file, which I would like to avoid. Do you have a solution ?

**Comment by coolacid** [comment]
That would be more of a MISP requirement, as MISP uses the file. 

You could generate the file on startup by volume mounting `/custom-entrypoint.sh` and running commands. 

This would not stop the details being available in the file. 

Alternatively, you could add another docker instance that is a mail handler that MISP could connect to, which would then ship the email off to your exchange.

Or, finally, add an allowlist to your exchange to accept emails from the MISP server.
