### ISSUE TITLE
Cortex plugin disabled during bootstrap

### ISSUE THREAD

**Issue by thezolin** [coolacid/docker-misp#212]
Hi All, 

Do you know how I can keep cortex plugin enabled.? 

Actually this plugin is disabled during bootstrap, but I need to keep it enabled. 

I have tried to comment the line at server/files/enrtrypoint_nginx.sh but no success. 

Thank you in advance.

**Comment by coolacid** [comment]
Cortex is disabled during the first initialisation because it's not configured yet. 

Change the settings once you have MISP started.

**Comment by thezolin** [comment]
So, 

I have my cortex plugin configured on config.php file. 
If I change anything on docker-compose.yml after container restart Cortex plugin is disable.

**Comment by coolacid** [comment]
Did you turn off the inial configuration ENV variable?

**Comment by thezolin** [comment]
Hi Jason, 

Where? because this is my .env file content:
![image](https://user-images.githubusercontent.com/36763110/224349752-b0c0e795-b785-444b-957b-04062bdb8a3e.png)

**Comment by coolacid** [comment]
https://github.com/coolacid/docker-misp/blob/master/docker-compose.yml#L42

**Comment by thezolin** [comment]
Hi Jason, 
Thanks for your quick response. 

I set this variable to false on docker-compose.yml file, but still the same. After container recreation, Cortex plugin still disable during startup. 

![image](https://user-images.githubusercontent.com/36763110/224643551-123cf514-06de-4fb8-9f4e-989960b07a79.png)
