### ISSUE TITLE
Migrate database from old misp (v2.4.132) to new misp(v2.4.169)

### ISSUE THREAD

**Issue by srPuebla** [coolacid/docker-misp#216]
Hi,
At the file /server/files/entrypoint_nginx.sh you have the method "init_mysql()" where the db is initialized. It tests that "attributes" table already exists. However, when there are important changes on the database file "misp\MISP2\INSTALL\MYSQL.sql" on misp (for example Between v2.4.147 vs v2.4.150 or v2.4.132 vs v2.4.169) you get the message "Database has already been initialized" on deploying the new version (Cause it verifies that attributes table exists)
Do you know if there is a way to migrate the database to the last one model?
Thanks so much!
Regards

**Comment by coolacid** [comment]
MySQL initialization should only happen the first time. 

DB upgrades are done by the application itself, not on restart.

**Comment by srPuebla** [comment]
Ahh, yeah. I got it. Thanks so mucho coolacid!
