### ISSUE TITLE
Support Request: Docker scout point out a lot of vulnerabilities on layers's images

### ISSUE THREAD

**Issue by Nicolas-Pellletier** [coolacid/docker-misp#223]
Hello, 

According to Docker Scout, there are a huge bunch of critical/High vulnerabilities on the docker images (see below):
Is there anything that could be done in order to fix these vulnerabilities ? 
Is it safe to run it in prod environment ?

------

![image](https://github.com/coolacid/docker-misp/assets/126868918/c28121e1-e295-4551-87d0-3336ddcebfbf)

![image](https://github.com/coolacid/docker-misp/assets/126868918/1c32b9d3-159f-44ca-b198-527aec70082f)

![image](https://github.com/coolacid/docker-misp/assets/126868918/6cc1d43a-c985-4160-9f02-26712aac0ff0)

![image](https://github.com/coolacid/docker-misp/assets/126868918/2aeb9722-da0c-4c78-a8a9-cdb17cc7d61d)

![image](https://github.com/coolacid/docker-misp/assets/126868918/60208ee6-6768-4bb6-86a4-4370389c0867)

Thanks

**Comment by coolacid** [comment]
Each version is built with the versions available at the time of the build. You can upgrade images to get the latest versions.
