### ISSUE TITLE
Error when accessing Events with Proposal page

### ISSUE THREAD

**Issue by GurBal** [coolacid/docker-misp#226]
Getting "An internal error has occurred" when accessing Home -> Events with Proposal page. Below is the entry logged in error.log file:
`
2023-06-18 17:36:04 Error: [PDOException] SQLSTATE[HY000]: General error: 3065 Expression #2 of ORDER BY clause is not in SELECT list, references column 'misp.ShadowAttribute.type' which is not in SELECT list; this is incompatible with DISTINCT
Request URL: /events/proposalEventIndex
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(715): DboSource->execute()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1226): DboSource->fetchAll()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3053): DboSource->read()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3025): Model->_readDataSource()
#6 /var/www/MISP/app/Controller/EventsController.php(3695): Model->find()
#7 [internal function]: EventsController->proposalEventIndex()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#11 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
`
Can someone point to what the issue might be?

**Comment by coolacid** [comment]
Please open an issue with MISP as this would be a application error, not a docker error.
