### ISSUE TITLE
Outdated version

### ISSUE THREAD

**Issue by thezolin** [coolacid/docker-misp#228]
Hi All, 

Does anyone have an idea when this container will be updated? 

![image](https://github.com/coolacid/docker-misp/assets/36763110/69fd0049-617d-4821-ab56-309289f26d21)

Thanks!

**Comment by derfel1989** [comment]
Hi @coolacid, any chance to let us know when the new release will be available?

Thank you.

**Comment by coolacid** [comment]
You'll probably find the error in the actual error logs in the logs directly. 

It's possible MISP isn't updating the Database. exec as the `www-data` user into the docker container into a bash shell, you're commands may vary: 

```
docker compose exec -u www-data misp bash
```

When in the docker shell, run the MISP updates: 

```
app/Console/cake admin runUpdates
```

**Comment by derfel1989** [comment]
Much appreciated for the quick response and support. I will test it.

**Comment by derfel1989** [comment]
It worked like a charm. Once again, thank you so much.

Below are the steps that I followed on portainer.

**Step 1**

![msedge_Q8DoTaqkVR](https://github.com/coolacid/docker-misp/assets/46175778/847d1b80-0b2f-447b-b0f5-7d273cf62622)

**Step 2**

![msedge_qt3k07Ulva](https://github.com/coolacid/docker-misp/assets/46175778/54e122c6-7db0-4ea0-826c-5855222cde8d)


**Step 3**

![msedge_AgtdornEOc](https://github.com/coolacid/docker-misp/assets/46175778/a6a175f6-36c6-4a7b-95c1-142bcdaf2b9c)

**Comment by Moorocks** [comment]
Hi @coolacid @derfel1989,

My version is .168, so I would like to do an update. 

This docker was setup on a server few months back and I guess it was not installed using docker compose I guess. The old staff might have installed by cloning and then building the docker image. 

I'm assuming the above situation. 

Could you please guide me how to perform an update of this docker image?
