### ISSUE TITLE
 INSTALL_NODB.sh - Syntax error?

### ISSUE THREAD

**Issue by fair2middlin** [coolacid/docker-misp#230]
I am getting the below error when I  run - D:\misp-docker>docker-compose up

 => CACHED [web 10/21] RUN echo "ALL ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers                                      0.0s
 => ERROR [web 11/21] RUN bash INSTALL_NODB.sh -A -u                                                               2.2s
------
 > [web 11/21] RUN bash INSTALL_NODB.sh -A -u:
0.368 INSTALL_NODB.sh: line 73: syntax error near unexpected token `$'{\r''
'.368 INSTALL_NODB.sh: line 73: `MISPvars () {

**Comment by coolacid** [comment]
This.. isn't an issue with this repo? It's not even called anywhere in the build...
