### ISSUE TITLE
Support Request for threat feeds update

### ISSUE THREAD

**Issue by Moorocks** [coolacid/docker-misp#231]
Hi there,

We are using this docker container to manage misp.
However I'm not sure if there's any configuration already set which is updating the threat feeds.

I can see in the misp manual that we need to set a cron job to update threat feeds regularly, however in your misp docker container there is no cron job set.

But if you go to jobs options in MISP UI, I can see that threat feeds are being updated.

Can I know how this is happening?

The reason why Iam asking this is because if I know when the update is happening, then our siem can pull the threat feeds once threat feeds are updated in the misp.

**Comment by coolacid** [comment]
Feed updates are configured here: https://github.com/coolacid/docker-misp/blob/master/docker-compose.yml#L43-L44

Set the UserID that should be used for feed updates, and what feed IDs you want to update.

**Comment by Moorocks** [comment]
Hi @coolacid, 
I can see that cron job is already set in entrypoint_cron.sh file. 

https://github.com/coolacid/docker-misp/blob/master/server/files/entrypoint_cron.sh

I can see that you configured the feed update to 2:30 AM everyday morning. 

I believe I can change these configurations according to my environment. 

Also in that file, you defined cron updates for sync servers. Does that mean that if I have any sync server setup, do I need to modify these times as well?
You defined the code to run the cron updates for sync servers for every 1 minute ( push and pull).
