### ISSUE TITLE
Docker upgrade 

### ISSUE THREAD

**Issue by Moorocks** [coolacid/docker-misp#233]
Hi @coolacid ,

My version is .168, so I would like to do an update. 

So yesterday I have installed your docker image in my local server (setup on linode). When I installed the docker and ran the image using docker-compose, the application is on the updated level.

However, the application version in my company is 2.4.168. 
I would like to update that version, but I'm unable to find docker-compose.yml file.
I'm assuming that my old staff has cloned git repo and built a new image from it. So they might have not use docker-compose to run the docker.
In this case, would it be possible to upgrade the docker-image?

I'm trying to find the docker.compose yml file so that I can upgrade to the latest version or override with any other version.
However I couldn't find it.

I tried navigating to the directory:

/var/www/MISP/app

Attach the ss below for reference:

<img width="1785" alt="Screenshot 2023-09-22 at 12 26 03 pm" src="https://github.com/coolacid/docker-misp/assets/143619572/27c068d5-d03a-4d6e-91e2-9403d169820b">

**Comment by palcica** [comment]
try `locate docker-compose`

**Comment by coolacid** [comment]
Sorry, this isn't a support site. We have no details on how your company might have deployed a docker image.
