### ISSUE TITLE
upgrade to latest image

### ISSUE THREAD

**Issue by palcica** [coolacid/docker-misp#234]
Hi, after upgrading from [core-v2.4.171a]  to [core-v2.4.176a] login doesnt work. 

error is:
`2023-09-25 09:18:37 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'User.totp' in 'field list'
Request URL: /users/login?_=1695626305412
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(715): DboSource->execute()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1226): DboSource->fetchAll()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3053): DboSource->read()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3025): Model->_readDataSource()
#6 /var/www/MISP/app/Controller/UsersController.php(1200): Model->find()
#7 [internal function]: UsersController->login()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#11 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#12 {main}`

when reverting back to [core-v2.4.171a] everything works again.

Any idea?

**Comment by sva-mk** [comment]
Hey @palcica,
please check out [this solution](https://github.com/coolacid/docker-misp/issues/228#issuecomment-1726046353) from @coolacid.
Updating the Database solved the issue for me.
