### ISSUE TITLE
[bug] MISP Modules not loading

### ISSUE THREAD

**Issue by coolacid** [coolacid/docker-misp#30]
`misp-modules - WARNING - MISP modules email_import failed due to Unable to import URLObject, pyfaup missing`

`MISP modules ransomcoindb failed due to No module named 'expansion._ransomcoindb'`

See #26

**Comment by coolacid** [comment]
init file for ransomcoindb was patched upstream, no need to keep this open.

**Comment by seanthegeek** [comment]
This was patched upstream, but Docker will still clone out misp-modules in an older state as tag v2.4.121, right? 

https://github.com/MISP/misp-modules/releases/tag/v2.4.121

https://github.com/MISP/misp-modules/commit/6111f02f59572f52a5401fb78d1577a5960ff098

**Comment by coolacid** [comment]
Correct.

**Comment by seanthegeek** [comment]
So what would be the best practice way of ensuring my instance gets the fix now, but doesn't break my ability to upgrade when the next release tag is set?

**Comment by coolacid** [comment]
You could make your own docker image based on mine, or use your fork without doing the PR.

**Comment by coolacid** [comment]
You could make your own docker image based on mine, or use your fork without doing the PR. The only monkey patching I'm doing is where the docker build causes problems, def not going to get in the habit of fixing bugs that should be managed up stream.
