### ISSUE TITLE
Proxy / Traefik mode

### ISSUE THREAD

**Issue by Maddosaurus** [coolacid/docker-misp#34]
As discussed in [this twitter thread](https://twitter.com/mat_zilla/status/1232292708477210624), it might be a nice feature to support proxy deployments that are handling TLS connections for the MISP container, like [traefik](https://containo.us/traefik/) does.  
To get this to work, MISP would ideally have to be available on plain HTTP without the redirect to HTTPS. Unfortunately, this could introduce severe issues if docker-misp is run in this mode without an according proxy, as all communication (including login credentials) would be unencrypted between the host and client.  
Therefore, it should be discussed if there is a safe way to provide this alternative deployment, i.e. by providing a sample nginx config to mount into the container.

**Comment by coolacid** [comment]
I can totally see a reason to disable the https redirect. Specifically in cases where you are forced to use an upstream proxy (Mesos comes to mind). This means I really want to handle this case safely without requiring someone overload the config file, or manage their own image. 

At the very least, I'm going to split 80/443 nginx configuration files, then, maybe an environment file that comments out the 301 return from the 80 config file.

**Comment by coolacid** [comment]
Whelp, I started down the road, and realised that simply just not doing the redirect wouldn't work. 

Options:
1> Put two versions of `misp80` in `nginx/sites-available` and have a default symlink to the redirect, and a variable to change the symlink
2> Make PHP-FPM endpoint a variable (default the socket file) and expose the FPM endpoint (Do external proxies even support FPM endpoints?) 
3> Both and let the user decide.

**Comment by Maddosaurus** [comment]
At least regarding traefik, it looks like they've not implemented it currently but rather discuss this (since 2016) https://github.com/containous/traefik/issues/753. It might be that other proxies do support this, but I'm not sure about that.

**Comment by seanthegeek** [comment]
A better approach would be for the user to supply their own self signed SSL certificates in ./ssl, and configure their reverse proxy to trust that certificate. That way it's encrypted all the way without changes to docker. I'll put a TODO to document this.

https://github.com/containous/traefik/issues/364

**Comment by coolacid** [comment]
You don't always control the proxy, think AWS ELB or container management tools like Mesos. It doesn't expose those things as options. Plus, inside a closed network, you don't gain anything.
