### ISSUE TITLE
Increase max_execution_time in php.ini

### ISSUE THREAD

**Issue by seanthegeek** [coolacid/docker-misp#44]
The default `max_execution_time = 300` in `/etc/php/7.3/fpm/php.ini` is too short. This causes 502 gateway errors from nginx when doing simple tasks in the web UI, such as deleting a page of indicators. This timeout should be increased to 900.

**Comment by coolacid** [comment]
502 gateway error would be coming from nginx - not php. 
This points out I need to up the timeout in nginx and other places as well, not just PHP. 

https://easyengine.io/tutorials/php/increase-script-execution-time/

**Comment by coolacid** [comment]
Pushed a commit that matches the PHP timeout of 300 seconds (5 Minutes) into nginx read timeout. This *should* fix the issue. 

300 seconds is MISP recommended timeout value. 15 minutes seems long, and probably want to fix your work flow. 

I tried to get nginx to timeout, pulled events from circlu, deleted a page of events, then tried to delete a page of indicators in an event, came back to fast for me to trigger the timeout. Please build this, and test.

**Comment by coolacid** [comment]
Just got a report that nginx also has a file upload limit, need to also change that.
