### ISSUE TITLE
Increase timeouts for php-fpm and nginx

### ISSUE THREAD

**Issue by seanthegeek** [coolacid/docker-misp#46]
I misunderstood the issue I reported in issue #44. `php.ini` is configured to timeout after 300 seconds, but php-fpm and nginx each need to be configured to match.

In `/etc/php/7.3/fpm/php-fpm.conf`, add:

```
request_terminate_timeout = 300
```

In `/etc/nginx/sites-available/misp80-noredir`

Add the following line under the the `fastcgi_pass` directive

```
fastcgi_read_timeout 300;
```

**Comment by coolacid** [comment]
Already in master. Also added POST size too.
