### ISSUE TITLE
Suggestion: Make it "safe" to always run the INIT-gated code in the entrypoint

### ISSUE THREAD

**Issue by Kagee** [coolacid/docker-misp#49]
Apart from the mysql operation in entrypoint_nginx.sh,  it looks safe to INIT=true all the time.  - is there a reason the init_mysql could not check to see if a essential table already existed, and then skip running the install SQL script?

It shoud be enough to copy isDBup to something like isDBpopulated, and repace "SHOW STATUS" with something like "DESCRIBE logs". Then it will return an error code if the table does not exist. PR may come.

**Comment by coolacid** [comment]
Looking at this again, yeah, that's a sane statement. So a PR would totally be welcome!
