### ISSUE TITLE
MISP is unable to connect to TLS 1.3 servers

### ISSUE THREAD

**Issue by coolacid** [coolacid/docker-misp#50]
We force TLS version 1.3 as a security measure, however, MISP can't actually connect to TLS 1.3. 

MISP tracking: https://github.com/MISP/MISP/issues/5764

We need to keep MISP secure, but allow a lesser connection other then TLS 1.3.

**Comment by coolacid** [comment]
To track CakePHP issue: https://github.com/cakephp/cakephp/issues/14422

**Comment by RichieB2B** [comment]
There is now a PR for this upstream: https://github.com/cakephp/cakephp/pull/14425
Can you try this:
```
cd app/Lib/cakephp
git pull
git checkout 50e0ca7f9d791f8e98b02c5a63ee79a932051b4b
```
