### ISSUE TITLE
Timeout without published ports

### ISSUE THREAD

**Issue by codex38** [coolacid/docker-misp#54]
Hey

When accessing MISP directly via the docker bridge network, I am having issues where MISP isn't responding when trying to add a user or changing user settings (like terms accepted, ...). In general it seems that it happens only in connection with POST request. Changing the MISP settings (which happen via Ajax I think) works without issues. After about 60sec the request just times out and the browser says that it received no response. During those 60sec no other action can be taken in a different browser tab with MISP.
Even with the debug output enabled, no information about the timeout is found in any of the log files. 

After a lot of trying around it seems, that this timeout only occurs, when MISP is not accessed via published ports. Since I have multiple docker containers running on my host, I prefer accessing them via a shared bridged network instead of having a bunch of published ports.

Steps to reproduce:

1. git clone https://github.com/coolacid/docker-misp.git
2. cd docker-misp
3. Comment out lines 28-30 in docker-compose.yml file where port publishing is defined
4. docker-compose up
5. Get IP of misp instance 'docker network inspect docker-misp_default | grep IPv4Add -B 3 | egrep "IP|Name"'
6. access 'https://misp-ip/' and login with admin@admin.test:admin
7. modify URL from https://localhost to https://misp-ip (since MISP redirects to the FQDN)
8. In MISP "Administration" -> "List Users"
9. Edit "admin@admin.test" user
10. Example: Click on checkbox "Terms Accepted"
11. Click on "Save"
12. Browser times out...

Any ideas how this issue can be resolved?

OS: Ubuntu 19.10
Docker Version: docker-ce 5:19.03.10~3-0~ubuntu-eoan

**Comment by coolacid** [comment]
I just tested this and had no issues. 

I don't expect this to be an issue specifically with this docker image. Since, it's all just strait networking. nginx would be listening on 0.0.0.0. This feels like a routing issue. 

Do the packets get into the container? Do packets get out of the container? What do the routes look like both inside, and outside the container?

**Comment by codex38** [comment]
Yes, you are right. It's a routing problem, because if I initiate the settings change from the docker host, it works without any issues. It is only a bit odd considering that the client can access misp for everything else without any problems, only during the PUT request the issue arises. In those cases it seems like nginx is not receiving any packets at all anymore and blocking for ~60sec while the client is trying to retransmit the packet every second.

**Comment by coolacid** [comment]
I wouldn't have a clue as to why this image wouldn't work any differently then any other. However, Docker tries to be smart about how to handle ports, even in a bridged network. Double check firewall rules, and hits too. 

What I typically do when I have multiple web services behind docker is implement nginx or haproxy in front of the service which handles SSL and vhosts. Then assign each service a CNAME in my DNS.

**Comment by codex38** [comment]
My bad, the issue seems to be entirely docker and misp unrelated. It seems that there is an issue with the wireguard connection to my server. The retransmitted network packets already don't make it from the client to the server let alone the docker container. Accessing MISP via ssh port forwarding works flawlessly, only the wireguard connection seems to cause some headaches...
