### ISSUE TITLE
MYSQL_PASSWORD env doesn't escape special characters

### ISSUE THREAD

**Issue by wkleinhenz** [coolacid/docker-misp#56]
Im  deploying the docker-misp docker compose and using a password like "^mke7G9j4ek4Id9ikTtof$&4NjuQ9^5&Ws" and the misp container was unable to connect to the data base, when checking the database.config file the password field contained parts of the password but also the word password  and extra spaces, after replacing it with the correct password the misp container is able to connect

**Comment by Kagee** [comment]
This is possibly because sed is used to inject the password into the config file. 
https://github.com/coolacid/docker-misp/blob/master/server/files/entrypoint_nginx.sh#L30
One possible solution is to use i.e. https://linux.die.net/man/1/envsubst instead of sed to inject the password

**Comment by Kagee** [comment]
It may be better to just suggest using long alfanumeric password, as it appears the official mysql docker does not escape special chars in supplied passwords and is not safe from "password injections attacks" either. https://github.com/docker-library/mysql/blob/master/8.0/docker-entrypoint.sh#L215

**Comment by coolacid** [comment]
Thanks @Kagee I'm of the same mindset. A longer AlfaNum would be better, cleaner and more supported in shells. If you need to use harder passwords, one can edit the configuration files - since they do not change afterwards. 

Thoughts @wkleinhenz ?

**Comment by wkleinhenz** [comment]
I think thats fine, it just kinda caught me off guard, would it be possible to add a statement into the documentation to mention this so that it doesn't become an issue for others

**Comment by coolacid** [comment]
Yeah, that's prudent.
