### ISSUE TITLE
Access to localhost was denied 

### ISSUE THREAD

**Issue by rbnor** [coolacid/docker-misp#57]
Windows 10, docker desktop, running powershell as admin, docker-compose up, it spins up, but i get: 

403 Access to localhost was denied you don't have authorization to view this page. HTTP ERROR 403

It comes to the "this is unsafe part", i proceed and then i get that, so i suspect its access rights related?  Assumed the image and config would be working so any suggestions to what to edit are welcome.

**Comment by coolacid** [comment]
Nothing in the image would have caused the 403. 

I don't even have a windows machine to test with. 

Can you screen shot? Might yield some clues.

**Comment by rbnor** [comment]
I just tried to reprouduce it at home and everything worked just fine. So
will have to figure out what the problem is at work, surely something local
at that computer.

**Comment by rbnor** [comment]
The issue was vmware host-d stealing 443 on localhost, closing this issue now.

**Comment by coolacid** [comment]
Thanks for the followup!
