### ISSUE TITLE
Unable to change password

### ISSUE THREAD

**Issue by rbnor** [coolacid/docker-misp#58]
Dry run, nothing changed, able to log in, but unable to do anything because of the change password bugging out on me: 

"Submitted new password cannot be the same as the current one"

Tried several passwords with 12+ length, upper and lower case, number, special char etc. No dice.

**Comment by coolacid** [comment]
Closed? What ended up being the problem?

**Comment by rbnor** [comment]
Not sure i want to tell you! ha ha, it was me mistaking the first one for
old password and the second for new, no idea why that would make sense..
but.. yeah. Thanks for the rapid response to issues in here anyways!  Even
tho they are self caused.

**Comment by coolacid** [comment]
Ticket for your own mistake? Story of my life.
