### ISSUE TITLE
PHP ZIP Support Missing

### ISSUE THREAD

**Issue by qh4t** [coolacid/docker-misp#64]
PHP ZIP support is required for some MISP feeds, including `https://urlhaus.abuse.ch/downloads/csv/` from the default feeds.

Error when trying to explore/preview the events remotely:

![misp_php_zip_error](https://user-images.githubusercontent.com/19820596/92836458-0c9ba580-f3a2-11ea-98f9-3bfa8499dbe6.png)

**Comment by coolacid** [comment]
Thanks! Merged that in. I'll see about cutting a new release as I think this is pretty important.
