### ISSUE TITLE
"NOREDIR=true"  seems not working

### ISSUE THREAD

**Issue by garanews** [coolacid/docker-misp#66]
Hello,
just found your docker image because need misp image without build for test purposes.
I need the minimum configuraiton, so I removed email part and misp modules from docker compose.
I tried to set "NOREDIR=true" in environment, If I open base url http, I being redirected to https.
If then I strip "s" on login url, the page is in http but if I try to insert credentials I got black holed.
So with that flag enabled:
http://1.2.3.4    -> redirect to https://1.2.3.4/users/login
 http://1.2.3.4/users/login   --> not redirect but can't login because black holed.

How can I setup your instance listening on http?

**Comment by coolacid** [comment]
Did you set the hostname? `NOREDIR` only flags the nginx web server to not redirect, however, MISP will still attempt to redirect if you have it configured.

**Comment by garanews** [comment]
in logs I see Configure NGINX | Disabling Port 80 Redirect
in compose I have
    ports:
      - "80:80"
      - "443:443"
    environment:
      - "HOSTNAME=http://1.2.3.4"
      - "REDIS_FQDN=redis"
      - "INIT=true"             # Initialze MISP, things includes, attempting to import SQL and the Files DIR
      - "CRON_USER_ID=1"        # The MISP user ID to run cron jobs as
      - "NOREDIR=true" # Do not redirect port 80
      - "DISIPV6=true" # Disable IPV6 in nginx

**Comment by coolacid** [comment]
I'll have to look deeper - the NOREDIR was really intended for people that have a proxy that handles SSL in front of the docker image. There was never a goal to allow non-SSL connections to MISP. 

The build will create self-signed certs by default - is there a reason you can't use SSL?

**Comment by garanews** [comment]
yes, because in other app (like the hive) doesn't have skip ssl cert, so need to export cert from here, import cert there and configure...
for a dirty test, too much time... 
just want build something ready to go for testing purposes

**Comment by garanews** [comment]
so like default admin is fine, it would be better have also default apikey, but not possible I suppose... :)

**Comment by coolacid** [comment]
I'm pretty sure this is a redirect thing in MISP. If you see the `Disabling Port 80 Redirect` then the docker image isn't doing the redirect - which means the redirect is in MISP. Double check the actual config file to ensure it's listing http as opposed to https - again, MISP really doesn't like being non-ssl.

**Comment by garanews** [comment]
for sure is misp, so probably need have an image tuned in that way,
Meanwhile, is it possible to set a variable to specify the name of db?
in compose you have:
```
  db:
    image: mysql:8.0.19
    command: --default-authentication-plugin=mysql_native_password
    restart: always

```
I would have mysql instead db so I set the hostname.:
```

  mysql:
    image: mysql:latest
    container_name: mysql
    hostname: db

```

but it seems misp container doesn't resolve db... he resolve mysql :)

**Comment by coolacid** [comment]
You can set the database host and other configuration details in the docker-compose config. https://github.com/coolacid/docker-misp/blob/master/docker-compose.yml#L44
