### ISSUE TITLE
defaut creadentials are not working

### ISSUE THREAD

**Issue by vaibhavpandey86** [coolacid/docker-misp#67]
Hello All,

I have installed docker image "A (nearly) production ready Dockered MISP" from [https://github.com/coolacid/docker-misp](url).
I just edited the port in docker-compose.yml :
 ports:
      - "80:80"
      - "**8443**:443"

as my wazuh is already using that port number. Everything installed fine,and GUI is asking for credentials as well, which is supposed to be
admin@admin.test : admin
it is not working.
Any help here please!!!

**Comment by coolacid** [comment]
We make no changes to the default credentials. I would suggest you run a `docker-compose rm` to ensure there is no existing database volumes mounted, or ensure the volume mount for the database is somewhere you expect and can delete the data as needed.

**Comment by vaibhavpandey86** [comment]
thank you so much.. it was some different error.
it got fixed now.
