### ISSUE TITLE
MISP Galaxy Data Incorrect

### ISSUE THREAD

**Issue by NomisRenarc** [coolacid/docker-misp#70]
hi all,

based on this build, I have noticed that the galaxy/tag data is incorrect for the MITRE ATT&CK Framework.
the IDs are incorrect, is this something custom for this build or is the feed from CIRCL the issue?

regards

**Comment by coolacid** [comment]
MISP Galaxy data is here: https://github.com/MISP/misp-galaxy/issues?q=is%3Aissue+is%3Aopen+label%3A%22topic%3A+att%26ck%22
