### ISSUE TITLE
Cannot build images

### ISSUE THREAD

**Issue by birladeanuadrian** [coolacid/docker-misp#72]
Whenever I try to build the images using **build-docer-compose.yml**, docker tries to install all versions of requests, then installation fails when trying to install a very old version of requests.
[error.txt](https://github.com/coolacid/docker-misp/files/5688648/error.txt)

Can anyone help me? Thanks.

**Comment by coolacid** [comment]
Fantastic. This is probably related to https://github.com/pypa/pip/issues/9168 which I learned about a few days ago. 

The python images are versioned for python, but images get updated with latest PIP. I'll look at forcing the legacy parser later today.

**Comment by coolacid** [comment]
Did you make any changes to the docker files? To prep for new versions of modules, I did a full rebuild and had no problems building.

**Comment by coolacid** [comment]
Uhg. Got it to fail on docker-hub build. Working on a temp fix.

**Comment by birladeanuadrian** [comment]
Hi,
I also checked now and everything works fine. Thanks!
