### ISSUE TITLE
Workers error conection refuse

### ISSUE THREAD

**Issue by IrArTr** [coolacid/docker-misp#76]
there is a problem when I install the docker image can not start the Workers 
Start Workers....
Error: connection refused
#0 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(23): Redis->pconnect('127.0.0.1', 6379, 5, '236')
#1 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(18): RedisApi->establishConnection()
#2 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Redis.php(168): RedisApi->__construct('127.0.0.1', '6379', 5, NULL)
#3 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque.php(102): Resque_Redis->__construct('127.0.0.1', '6379', NULL)
 #4 /var/www/MISP/app/Plugin/CakeResque/Console/Command/CakeResqueShell.php(77): Resque::redis()
 #5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(451): CakeResqueShell->startup()
 #6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand('stop', Array)
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
 #8 /var/www/MISP/app/Console/cake.php(32): ShellDispatcher::run(Array)
 #9 {main}

**Comment by coolacid** [comment]
Is redis running?

I suggest reading the documentation: https://github.com/coolacid/docker-misp#developmenttest

**Comment by IrArTr** [comment]
Yes, I am using Development/Test,
yesterday the image working normally, 
and today I wanted to install it in another machine and I had this problem

**Comment by coolacid** [comment]
The error indicates it can't connect to Redis, try re-installing, or provide more details.

**Comment by pemontto** [comment]
I believe the problem is that the latest version now ships with `127.0.0.1` instead of `localhost` in `/var/www/MISP/app/Plugin/CakeResque/Config/config.php`.

On a fresh install it looks like this

```php
[..]x
$config['CakeResque'] = array(
	'Redis' => array(
		'host' => '127.0.0.1',		// Redis server hostname
		'port' => 6379,				// Redis server port
		'database' => 0,			// Redis database number
		'namespace' => 'resque',	// Redis keys namespace
		'password' => null			// Redis password
	),
[..]
```

Adding a to `    sed -i "s/'host' => '127.0.0.1'.*/'host' => '$REDIS_FQDN',          \/\/ Redis server hostname/" "/var/www/MISP/app/Plugin/CakeResque/Config/config.php"
` to https://github.com/coolacid/docker-misp/blob/066f5c8dfac8b64698ae567e2ff13a5787b0e256/server/files/entrypoint_nginx.sh#L16 should do the trick.

**Comment by coolacid** [comment]
Thanks for digging into that. I have on a number of occasions considered writing PHP or Python code to parse these files, make the changes I want, and re-write the files back.

**Comment by coolacid** [comment]
I just pushed a B tag with the fix, give it a couple hours to show up on docker hub.
