### ISSUE TITLE
Galaxy 2.0 Timeframe?

### ISSUE THREAD

**Issue by k7leafclover** [coolacid/docker-misp#84]
@coolacid - Do you have an approximate timeframe to incorporate the [Galaxy 2.0 enhancements](https://github.com/MISP/MISP/releases/tag/v2.4.135) from MISP `2.4.135`? Thank you!

**Comment by coolacid** [comment]
Current released version of the docker image is 2.4.135 already. Did you update? Is there more work to migrate to 2.0?

**Comment by k7leafclover** [comment]
I must have missed it. Will test soon.  Thank you for the rapid follow-up!
