### ISSUE TITLE
Discussion future misp/misp-docker vs. coolacid/docker-misp

### ISSUE THREAD

**Issue by 8ear** [coolacid/docker-misp#85]
Hi @coolacid  @Kagee ,
How we want to make the furture of misp/misp-docker?

Should we develop more and more the solution here from @coolacid or more or less a new one or to check how we can improve the current solution (which is very bad and buggy).

My goal is that on the end:
- [ ] Git repo must be checked via dependabot and a lot of other Github workflows so that the most is automated
- [ ] quay.io / hub.docker.com official images daily build
- [ ] ensure that all the time every last 10 versions are build

Therefore I think the best is always if the dockerfile itself is included in the orginal repository because it must be checked berfore a new tag is set. and then the code fits always to the dockerfile. Then you have your misp-docker repo which is has all the other makefile, scripts, dockrer-compose file, automation files etc.

Open questions for me:
- Why you use not the repo submodules? (this make a difference between a MISP with this docker container and with baremetal MISP)
- Why you do not removed the nginx from core? normally php-fpm should be enough or?

What is your meaning here? How you see the future?

**Comment by coolacid** [comment]
Many months ago, I had this exact conversation with @iglocska 

I'm not sure how much dependabot is going to help here, the docker system doesn't have any dependencies, and I have to assume the code upstream does their own dependency validations. I could be wrong here, but I've never seen a pure docker container require dependency checks. 

Daily builds are interesting and probably valid for development. I'd recommend two different repositories, one production tagged images only, and one development - I'd hate to have an enterprise accidentally use the wrong images. 

I've kept every tagged version in the repo - again, keeping dev vs prod repositories separated, prod should keep every build, and dev could keep the last $X available. 

I've wrestled with docker files in, and out of projects for years. Personally, in this case, I'm of the belief that all build tools should be separate from the rest of the project, this includes repository builds, container builds - I just find larger projects already get cluttered, and adding builds on top of that exaggerates it. Scripts, automation files, and the like has to be kept with the docker file, or the docker file can't add them to the image. 

One of my goals is to keep the images as small as possible - Repo-submodules just adds bloat. The sub-modules are pre-built to also keep anything required for building the packages outside of the distributed image. I can't remove nginx from core, I wouldn't be able to access CSS, JS, or Images.

**Comment by 8ear** [comment]
> Many months ago, I had this exact conversation with @iglocska
What was the result?


> Daily builds are interesting and probably valid for development. I'd recommend two different repositories, one production tagged images only, and one development - I'd hate to have an enterprise accidentally use the wrong images.
> I've kept every tagged version in the repo - again, keeping dev vs prod repositories separated, prod should keep every build, and dev could keep the last $X available.
Yeah I think you missunderstand me. The production image must be build daily so that the latest security patches are in and they use not an old image.
My goal is to have daily build docker images for perhaps the last 5 or more versions where the dockerfile is fixed from the code repo and we build it only with the newest base image. Therefore repos in dockerfile with latest are not possible it is the same reason why misp/misp use their submodules also tagged to a specific commit.




> 
> 
> Many months ago, I had this exact conversation with @iglocska
> 
> I'm not sure how much dependabot is going to help here, the docker system doesn't have any dependencies, and I have to assume the code upstream does their own dependency validations. I could be wrong here, but I've never seen a pure docker container require dependency checks.
> 
> Daily builds are interesting and probably valid for development. I'd recommend two different repositories, one production tagged images only, and one development - I'd hate to have an enterprise accidentally use the wrong images.
> 
> I've kept every tagged version in the repo - again, keeping dev vs prod repositories separated, prod should keep every build, and dev could keep the last $X available.
> 
> I've wrestled with docker files in, and out of projects for years. Personally, in this case, I'm of the belief that all build tools should be separate from the rest of the project, this includes repository builds, container builds - I just find larger projects already get cluttered, and adding builds on top of that exaggerates it. Scripts, automation files, and the like has to be kept with the docker file, or the docker file can't add them to the image.

> One of my goals is to keep the images as small as possible - Repo-submodules just adds bloat. The sub-modules are pre-built to also keep anything required for building the packages outside of the distributed image.
I like the way that you want to reduce the image. But on the end you install the submodules also there is only the difference that you use latest and not the tagged one.

> I can't remove nginx from core, I wouldn't be able to access CSS, JS, or Images.
Why? via docker volume you can mount the same path on NGINX as in misp. it is then the same way is it is done for wordpress:fpm with nginx.

**Comment by coolacid** [comment]
> What was the result?

I had the option of moving my docker image under the MISP project. We just never pulled the trigger since we wanted to discuss with other maintainers. 

> Yeah I think you missunderstand me. The production image must be build daily so that the latest security patches are in and they use not an old image.

As a security person, I disagree. You're implementing random changes to an expected containerised implementation. This fully breaks change and vulnerability management. As it is, I'm already having to deal with the base python images updating pip causing downstream projects to break due to regressions. If there is a security patch of high enough importance, please open an issue with the CVE details, and I'm happy to push a new `letter` build. 

> My goal is to have daily build docker images for perhaps the last 5 or more versions where the dockerfile is fixed from the code repo and we build it only with the newest base image. Therefore repos in dockerfile with latest are not possible it is the same reason why misp/misp use their submodules also tagged to a specific commit.

I don't understand the goal here. Please elaborate what problem you're trying to solve. 

> It helps to keep github workflows up to date. Which I want to introduce.

As I understand it, dependabot validates dependencies for projects by looking at, for example the requirements.txt of python projects and monitor for dependency updates. https://dependabot.com/blog/dependabot-now-supports-docker/ Says it monitors the FROM line and submits a PR when there is an updated version. This won't work, again, enterprises already have proven and accepted versions for base OSes. This includes in Dockerfiles. Additionally, base OS updates can contain very drastic changes. I don't have the time to do full user acceptance testing every time a new base OS is released. I've already found a number of items that needed resolving in MISP and it's modules due to using the base images I use.

> I like the way that you want to reduce the image. But on the end you install the submodules also there is only the difference that you use latest and not the tagged one.

I suggest you go back and look at the dockerfile. All the submodules are built in a seperate docker image, and then the built packages are installed in the distributed image. This means, all the development tools used to build the packages aren't in the final image. This not only reduces the image size, but also increases the security of the images. 

You're right, I should be using tagged submodules. That slipped my mind when I originally built the dockerfiles. I should revisit that. 

> > I can't remove nginx from core, I wouldn't be able to access CSS, JS, or Images.
> 
> Why? via docker volume you can mount the same path on NGINX as in misp. it is then the same way is it is done for wordpress:fpm with nginx.

I... I don't volume mount any CSS, JS or images - at all. Looking at how wordpress:fpm mounts things - I'd have to assume it's entrypoint copies the files during the startup. Maybe via rsync? I'm not sure. While I'm all for ripping out different services and placing them where they belong - That's not a direction I'm willing to go. Sorry.

**Comment by 8ear** [comment]
First I will say thank you to you for this great discussion and time from you.


Why daily build docker container?
So from my perspective everyone decide itself when he want to update his docker container. Because without any additional like watchtower or so docker does never automatically update your running container without a user action.
But if you decide to “patch” your container with latest security patches this cannot be done until there exists a container for that. 
In your current Setup the guys have only the chance to build the container on her own or to hope the latest misp version is not so old, which can bring other downsides.
“patching” of docker container and vulnerability management works in other way as for bare metal installations. For bare metal installation you must only add a new software package if you any because the os Updates is take over to company it and not to software maintainer. This changed with docker. As docker maintainer, you must fulfill he role as patchmananger, software packager, vulnerability engineer, ....
That’s the reason why a container should be scanned before his is published as prod and why from the same container a daily build is required to include the latest so security patches,  it all other should be tagged.

can you explain a little more which connection your Nguni have with the fpm? I think couldn’t follow you.

Only a notice with WordPress:
there is no rsync or entrypoint copies. It is easier.
You make a volume where the misp data are and on ngoni you mount the same data volume as read-only so that nginx can deliver the static objects.

**Comment by coolacid** [comment]
> First I will say thank you to you for this great discussion and time from you.

Your welcome. 

> Why daily build docker container?
> So from my perspective everyone decide itself when he want to update his docker container. Because without any additional like watchtower or so docker does never automatically update your running container without a user action.

Many enterprise tools related to deploying docker images have the option to automatically pull the latest. That is why every one of my builds is tagged to a version that is immutable. What you get on one deploy, is the exact same as you get on another. 

Let's provide a different example. I test docker images in a dev, stage, and prod environment. These could be weeks between pulls. If the images are not immutable, what I pull in dev may not match the other environments. 

> But if you decide to “patch” your container with latest security patches this cannot be done until there exists a container for that.

Again, I maintain and use these exact images in an enterprise as well as a community installation. I know how this works. If there's a CVE I miss, I'm happy to have an issue raised, and I can cut a release within hours. I have over a dozen personal security threat intel friends that use my docker images. They have my cell phone number. It wouldn't take long for me to be made aware of a critical vulnerability. 

> In your current Setup the guys have only the chance to build the container on her own or to hope the latest misp version is not so old, which can bring other downsides.

If they are that worried, then they are probably already building images on their own. I know of at least Security Operation Centre that does this. 

> “patching” of docker container and vulnerability management works in other way as for bare metal installations. For bare metal installation you must only add a new software package if you any because the os Updates is take over to company it and not to software maintainer. This changed with docker. As docker maintainer, you must fulfill he role as patchmananger, software packager, vulnerability engineer, ....

Patching isn't a science. I can't define the risk acceptance for anyone except myself, and the people that trust me to do it for them. As such, where my risk acceptance leads is where my projects will be placed. Others may have less tolerable risk, and as such they maintain their own builds to their specifications. 

> That’s the reason why a container should be scanned before his is published as prod and why from the same container a daily build is required to include the latest so security patches, it all other should be tagged.

I wrote vulnerability management guidelines. You're attempting to tell me what everyone else's risk profiles are. This is a fundamental problem with security people (myself included) and needs to stop. Again, I take risk very seriously. 

> can you explain a little more which connection your Nguni have with the fpm? I think couldn’t follow you.
> 
> Only a notice with WordPress:
> there is no rsync or entrypoint copies. It is easier.
> You make a volume where the misp data are and on ngoni you mount the same data volume as read-only so that nginx can deliver the static objects.
 
I'm sorry, I'm not taking time to dive into this. The design decisions I've made has to stick. What you're suggesting is not backwards compatible, and as such would break a lot of peoples implementations. This isn't changing. 

> I thought about what you told about the naming and I think with the naming you are right. There is a need for v(MISP version)(script version).

Not only that, you'd need v[MISP Version][My Version][Build Version] and a latest for each. This would complicate, and cause new people to the project confusion.

**Comment by 8ear** [comment]
Hi,
Thanks for your answers.

**Comment by coolacid** [comment]
No, thank you for bringing ideas forth. I just have very specific reasons why things are built as such.
